import type { PracticeProblem } from '../types';

export const BASICS_PROBLEMS: PracticeProblem[] = [
  {
    id: 'py-001',
    problemNumber: 1,
    slug: 'sum-of-two-numbers',
    title: 'Sum of Two Numbers',
    difficulty: 'Easy',
    topic: 'Basics',
    topics: ['Basics', 'Math'],
    relatedDay: 1,
    relatedCurriculumTopic: 'Introduction to Python & Arithmetic',
    description: 'Read two space-separated integers `a` and `b` from standard input and print their arithmetic sum.',
    inputFormat: 'A single line containing two space-separated integers `a` and `b`.',
    outputFormat: 'Print a single integer representing the sum `a + b`.',
    constraints: '-10^9 <= a, b <= 10^9',
    examples: [
      { input: '5 7', output: '12', explanation: '5 + 7 = 12' },
      { input: '-3 10', output: '7', explanation: '-3 + 10 = 7' },
    ],
    starterCode: '# Read two space-separated integers\na, b = map(int, input().split())\n\n# Calculate and print the sum\n',
    hints: [
      'Use input().split() to break the input into tokens.',
      'Convert each token to an integer using map(int, ...).',
      'Print the result of adding the two numbers with print(a + b).'
    ],
    publicTestCases: [
      { input: '5 7', expectedOutput: '12' },
      { input: '-3 10', expectedOutput: '7' },
      { input: '0 0', expectedOutput: '0' },
    ],
    hiddenTestCases: [
      { input: '1000000000 1000000000', expectedOutput: '2000000000' },
      { input: '-500 -500', expectedOutput: '-1000' },
      { input: '0 -42', expectedOutput: '-42' },
    ],
    solution: {
      approach: 'Parse the two integers from standard input and output their sum using the + operator.',
      code: 'a, b = map(int, input().split())\nprint(a + b)',
      timeComplexity: 'O(1)',
      spaceComplexity: 'O(1)',
    },
    isPublished: true,
  },
  {
    id: 'py-002',
    problemNumber: 2,
    slug: 'rectangle-area-and-perimeter',
    title: 'Rectangle Area and Perimeter',
    difficulty: 'Easy',
    topic: 'Basics',
    topics: ['Basics', 'Math', 'Geometry'],
    relatedDay: 1,
    relatedCurriculumTopic: 'Python Operators & Expressions',
    description: 'Given the length `L` and width `W` of a rectangle on two separate lines, calculate and print its area and perimeter separated by a space.',
    inputFormat: 'First line contains integer `L` (length).\nSecond line contains integer `W` (width).',
    outputFormat: 'Print two space-separated integers: `Area Perimeter`.',
    constraints: '1 <= L, W <= 10^6',
    examples: [
      { input: '5\n3', output: '15 16', explanation: 'Area = 5 * 3 = 15, Perimeter = 2 * (5 + 3) = 16' },
      { input: '10\n10', output: '100 40', explanation: 'Area = 10 * 10 = 100, Perimeter = 2 * (10 + 10) = 40' },
    ],
    starterCode: 'l = int(input())\nw = int(input())\n\n# Compute area and perimeter\n',
    hints: [
      'Area of a rectangle is length * width.',
      'Perimeter of a rectangle is 2 * (length + width).',
      'Print both values separated by a space using print(area, perimeter).'
    ],
    publicTestCases: [
      { input: '5\n3', expectedOutput: '15 16' },
      { input: '10\n10', expectedOutput: '100 40' },
    ],
    hiddenTestCases: [
      { input: '1\n1', expectedOutput: '1 4' },
      { input: '1000\n500', expectedOutput: '500000 3000' },
      { input: '7\n12', expectedOutput: '84 38' },
    ],
    solution: {
      approach: 'Read length and width sequentially. Compute area as l * w and perimeter as 2 * (l + w).',
      code: 'l = int(input())\nw = int(input())\nprint(l * w, 2 * (l + w))',
      timeComplexity: 'O(1)',
      spaceComplexity: 'O(1)',
    },
    isPublished: true,
  },
  {
    id: 'py-003',
    problemNumber: 3,
    slug: 'celsius-to-fahrenheit-converter',
    title: 'Celsius to Fahrenheit Converter',
    difficulty: 'Easy',
    topic: 'Basics',
    topics: ['Basics', 'Math'],
    relatedDay: 1,
    relatedCurriculumTopic: 'Arithmetic Operations & Floats',
    description: 'Read a floating-point temperature in Celsius `C` and convert it to Fahrenheit using the formula `F = (C * 9/5) + 32`. Print the resulting temperature rounded to 2 decimal places.',
    inputFormat: 'A single float `C` on one line.',
    outputFormat: 'Print the Fahrenheit temperature formatted to exactly 2 decimal places.',
    constraints: '-273.15 <= C <= 1000.0',
    examples: [
      { input: '0', output: '32.00', explanation: '0 Celsius is 32 Fahrenheit.' },
      { input: '100', output: '212.00', explanation: '100 Celsius is 212 Fahrenheit.' },
      { input: '36.6', output: '97.88', explanation: '(36.6 * 9/5) + 32 = 97.88' },
    ],
    starterCode: 'c = float(input())\n\n# Convert Celsius to Fahrenheit and print formatted to 2 decimals\n',
    hints: [
      'Use the formula f = (c * 9/5) + 32.',
      'Format output using f-strings: f"{f:.2f}".'
    ],
    publicTestCases: [
      { input: '0', expectedOutput: '32.00' },
      { input: '100', expectedOutput: '212.00' },
      { input: '36.6', expectedOutput: '97.88' },
    ],
    hiddenTestCases: [
      { input: '-40', expectedOutput: '-40.00' },
      { input: '25.5', expectedOutput: '77.90' },
      { input: '-273.15', expectedOutput: '-459.67' },
    ],
    solution: {
      approach: 'Convert float input with the standard conversion equation and format with f-string :.2f.',
      code: 'c = float(input())\nf = (c * 9 / 5) + 32\nprint(f"{f:.2f}")',
      timeComplexity: 'O(1)',
      spaceComplexity: 'O(1)',
    },
    isPublished: true,
  },
  {
    id: 'py-004',
    problemNumber: 4,
    slug: 'quotient-and-remainder',
    title: 'Quotient and Remainder',
    difficulty: 'Easy',
    topic: 'Basics',
    topics: ['Basics', 'Math'],
    relatedDay: 2,
    relatedCurriculumTopic: 'Integer Division & Modulo',
    description: 'Given two positive integers `dividend` and `divisor`, print the integer quotient (`//`) and remainder (`%`) separated by a space.',
    inputFormat: 'Two space-separated integers `dividend` and `divisor`.',
    outputFormat: 'Print `quotient remainder`.',
    constraints: '1 <= dividend <= 10^9, 1 <= divisor <= 10^9',
    examples: [
      { input: '17 5', output: '3 2', explanation: '17 // 5 = 3 and 17 % 5 = 2' },
      { input: '20 4', output: '5 0', explanation: '20 is cleanly divisible by 4.' },
    ],
    starterCode: 'dividend, divisor = map(int, input().split())\n\n# Compute and print quotient and remainder\n',
    hints: [
      'Python has the // operator for floor division and % for modulo.',
      'You can also use divmod(dividend, divisor).'
    ],
    publicTestCases: [
      { input: '17 5', expectedOutput: '3 2' },
      { input: '20 4', expectedOutput: '5 0' },
    ],
    hiddenTestCases: [
      { input: '100 7', expectedOutput: '14 2' },
      { input: '5 10', expectedOutput: '0 5' },
      { input: '999999999 1', expectedOutput: '999999999 0' },
    ],
    solution: {
      approach: 'Use the floor division // and modulo % operators.',
      code: 'dividend, divisor = map(int, input().split())\nprint(dividend // divisor, dividend % divisor)',
      timeComplexity: 'O(1)',
      spaceComplexity: 'O(1)',
    },
    isPublished: true,
  },
  {
    id: 'py-005',
    problemNumber: 5,
    slug: 'simple-interest-calculator',
    title: 'Simple Interest Calculator',
    difficulty: 'Easy',
    topic: 'Basics',
    topics: ['Basics', 'Math'],
    relatedDay: 2,
    relatedCurriculumTopic: 'Variables & Expressions',
    description: 'Calculate the Simple Interest for principal `P`, annual interest rate `R` (in %), and time `T` (in years). Formula: `SI = (P * R * T) / 100`. Print the interest amount rounded to 2 decimal places.',
    inputFormat: 'Three space-separated numbers: `P R T`.',
    outputFormat: 'Print the simple interest formatted to 2 decimal places.',
    constraints: '1 <= P <= 10^7, 0.1 <= R <= 100.0, 0.1 <= T <= 50.0',
    examples: [
      { input: '1000 5 2', output: '100.00', explanation: '(1000 * 5 * 2) / 100 = 100.00' },
      { input: '2500 7.5 3', output: '562.50', explanation: '(2500 * 7.5 * 3) / 100 = 562.50' },
    ],
    starterCode: 'p, r, t = map(float, input().split())\n\n# Calculate simple interest\n',
    hints: [
      'Parse the input as floats.',
      'Multiply p * r * t and divide by 100.',
      'Format output with f"{si:.2f}".'
    ],
    publicTestCases: [
      { input: '1000 5 2', expectedOutput: '100.00' },
      { input: '2500 7.5 3', expectedOutput: '562.50' },
    ],
    hiddenTestCases: [
      { input: '10000 10 1', expectedOutput: '1000.00' },
      { input: '500 4.25 2.5', expectedOutput: '53.12' },
      { input: '12345 6.78 4.5', expectedOutput: '3766.42' },
    ],
    solution: {
      approach: 'Compute (P * R * T) / 100 and print formatted to two decimal places.',
      code: 'p, r, t = map(float, input().split())\nsi = (p * r * t) / 100\nprint(f"{si:.2f}")',
      timeComplexity: 'O(1)',
      spaceComplexity: 'O(1)',
    },
    isPublished: true,
  },
  {
    id: 'py-006',
    problemNumber: 6,
    slug: 'swap-two-variables-without-temp',
    title: 'Swap Two Variables',
    difficulty: 'Easy',
    topic: 'Basics',
    topics: ['Basics', 'Variables'],
    relatedDay: 2,
    relatedCurriculumTopic: 'Variable Assignment & Tuple Packing',
    description: 'Read two values `a` and `b` on a single line. Swap their values and print `a` and `b` in the new order separated by a space.',
    inputFormat: 'Two space-separated values `a` and `b`.',
    outputFormat: 'Print the swapped values: `b a`.',
    constraints: 'Strings containing alphanumeric characters.',
    examples: [
      { input: 'Apple Banana', output: 'Banana Apple', explanation: 'Apple and Banana are swapped.' },
      { input: '10 20', output: '20 10', explanation: '10 and 20 are swapped.' },
    ],
    starterCode: 'a, b = input().split()\n\n# Swap variables a and b\n',
    hints: [
      'In Python you can swap variables in a single line: a, b = b, a.'
    ],
    publicTestCases: [
      { input: 'Apple Banana', expectedOutput: 'Banana Apple' },
      { input: '10 20', expectedOutput: '20 10' },
    ],
    hiddenTestCases: [
      { input: 'X Y', expectedOutput: 'Y X' },
      { input: 'Kriora Python', expectedOutput: 'Python Kriora' },
      { input: 'Same Same', expectedOutput: 'Same Same' },
    ],
    solution: {
      approach: 'Use Python tuple unpacking assignment `a, b = b, a`.',
      code: 'a, b = input().split()\na, b = b, a\nprint(a, b)',
      timeComplexity: 'O(1)',
      spaceComplexity: 'O(1)',
    },
    isPublished: true,
  },
  {
    id: 'py-007',
    problemNumber: 7,
    slug: 'last-digit-of-a-number',
    title: 'Last Digit of a Number',
    difficulty: 'Easy',
    topic: 'Basics',
    topics: ['Basics', 'Math'],
    relatedDay: 2,
    relatedCurriculumTopic: 'Modulo Arithmetic',
    description: 'Given an integer `N`, find and print its last digit (the unit place digit). Note that the input can be negative, but the last digit should always be positive.',
    inputFormat: 'A single integer `N`.',
    outputFormat: 'Print the unit digit as a non-negative integer.',
    constraints: '-10^9 <= N <= 10^9',
    examples: [
      { input: '1234', output: '4', explanation: 'The unit digit of 1234 is 4.' },
      { input: '-987', output: '7', explanation: 'The unit digit of -987 is 7.' },
      { input: '0', output: '0', explanation: 'The unit digit of 0 is 0.' },
    ],
    starterCode: 'n = int(input())\n\n# Find and print the last digit\n',
    hints: [
      'Take the absolute value of the integer with abs(n).',
      'The last digit is simply abs(n) % 10.'
    ],
    publicTestCases: [
      { input: '1234', expectedOutput: '4' },
      { input: '-987', expectedOutput: '7' },
      { input: '0', expectedOutput: '0' },
    ],
    hiddenTestCases: [
      { input: '5', expectedOutput: '5' },
      { input: '-10', expectedOutput: '0' },
      { input: '999999999', expectedOutput: '9' },
    ],
    solution: {
      approach: 'Take the absolute value and compute modulo 10.',
      code: 'n = int(input())\nprint(abs(n) % 10)',
      timeComplexity: 'O(1)',
      spaceComplexity: 'O(1)',
    },
    isPublished: true,
  },
  {
    id: 'py-008',
    problemNumber: 8,
    slug: 'hours-minutes-seconds-converter',
    title: 'Seconds to Time Format',
    difficulty: 'Easy',
    topic: 'Basics',
    topics: ['Basics', 'Math'],
    relatedDay: 3,
    relatedCurriculumTopic: 'Time Arithmetic & Formatting',
    description: 'Given a total number of seconds `S`, convert it into hours, minutes, and remaining seconds in the format `HH:MM:SS` with 2-digit zero-padding.',
    inputFormat: 'A single non-negative integer `S`.',
    outputFormat: 'Print the time in `HH:MM:SS` format.',
    constraints: '0 <= S <= 86399 (one full day)',
    examples: [
      { input: '3665', output: '01:01:05', explanation: '3665s = 1 hour (3600s), 1 minute (60s), and 5 seconds.' },
      { input: '0', output: '00:00:00', explanation: '0 seconds is midnight.' },
      { input: '7200', output: '02:00:00', explanation: '7200s = 2 hours.' },
    ],
    starterCode: 'total_seconds = int(input())\n\n# Convert to HH:MM:SS format\n',
    hints: [
      'hours = total_seconds // 3600',
      'minutes = (total_seconds % 3600) // 60',
      'seconds = total_seconds % 60',
      'Use f-string padding: f"{hours:02d}:{minutes:02d}:{seconds:02d}".'
    ],
    publicTestCases: [
      { input: '3665', expectedOutput: '01:01:05' },
      { input: '0', expectedOutput: '00:00:00' },
      { input: '7200', expectedOutput: '02:00:00' },
    ],
    hiddenTestCases: [
      { input: '59', expectedOutput: '00:00:59' },
      { input: '86399', expectedOutput: '23:59:59' },
      { input: '3600', expectedOutput: '01:00:00' },
    ],
    solution: {
      approach: 'Calculate hours, minutes, and seconds using division and modulo, then zero-pad with :02d.',
      code: 's = int(input())\nh = s // 3600\nm = (s % 3600) // 60\nsec = s % 60\nprint(f"{h:02d}:{m:02d}:{sec:02d}")',
      timeComplexity: 'O(1)',
      spaceComplexity: 'O(1)',
    },
    isPublished: true,
  },
  {
    id: 'py-009',
    problemNumber: 9,
    slug: 'power-and-cube-calculation',
    title: 'Square and Cube Calculation',
    difficulty: 'Easy',
    topic: 'Basics',
    topics: ['Basics', 'Math'],
    relatedDay: 3,
    relatedCurriculumTopic: 'Exponentiation Operators',
    description: 'Given an integer `N`, print its square (`N^2`) and cube (`N^3`) separated by a space.',
    inputFormat: 'A single integer `N`.',
    outputFormat: 'Print `square cube`.',
    constraints: '-10^4 <= N <= 10^4',
    examples: [
      { input: '3', output: '9 27', explanation: '3^2 = 9, 3^3 = 27' },
      { input: '-4', output: '16 -64', explanation: '(-4)^2 = 16, (-4)^3 = -64' },
    ],
    starterCode: 'n = int(input())\n\n# Compute square and cube\n',
    hints: [
      'Use the ** exponentiation operator in Python: n ** 2 and n ** 3.'
    ],
    publicTestCases: [
      { input: '3', expectedOutput: '9 27' },
      { input: '-4', expectedOutput: '16 -64' },
      { input: '0', expectedOutput: '0 0' },
    ],
    hiddenTestCases: [
      { input: '10', expectedOutput: '100 1000' },
      { input: '-1', expectedOutput: '1 -1' },
      { input: '25', expectedOutput: '625 15625' },
    ],
    solution: {
      approach: 'Use the ** operator to compute n**2 and n**3.',
      code: 'n = int(input())\nprint(n ** 2, n ** 3)',
      timeComplexity: 'O(1)',
      spaceComplexity: 'O(1)',
    },
    isPublished: true,
  },
  {
    id: 'py-010',
    problemNumber: 10,
    slug: 'average-of-three-numbers',
    title: 'Average of Three Numbers',
    difficulty: 'Easy',
    topic: 'Basics',
    topics: ['Basics', 'Math'],
    relatedDay: 3,
    relatedCurriculumTopic: 'Arithmetic Mean & Precision',
    description: 'Read three floating-point numbers `a`, `b`, and `c` on a single line and print their arithmetic mean rounded to 2 decimal places.',
    inputFormat: 'Three space-separated numbers `a b c`.',
    outputFormat: 'Print the average formatted to 2 decimal places.',
    constraints: '-10^6 <= a, b, c <= 10^6',
    examples: [
      { input: '10 20 30', output: '20.00', explanation: '(10 + 20 + 30) / 3 = 20.00' },
      { input: '4.5 6.2 9.8', output: '6.83', explanation: '(4.5 + 6.2 + 9.8) / 3 = 6.8333... -> 6.83' },
    ],
    starterCode: 'a, b, c = map(float, input().split())\n\n# Compute average and print formatted to 2 decimal places\n',
    hints: [
      'Sum the three values and divide by 3.0.',
      'Format output with f"{avg:.2f}".'
    ],
    publicTestCases: [
      { input: '10 20 30', expectedOutput: '20.00' },
      { input: '4.5 6.2 9.8', expectedOutput: '6.83' },
    ],
    hiddenTestCases: [
      { input: '0 0 0', expectedOutput: '0.00' },
      { input: '-10 10 0', expectedOutput: '0.00' },
      { input: '100 200 301', expectedOutput: '200.33' },
    ],
    solution: {
      approach: 'Add the three values, divide by 3, and format to 2 decimal places.',
      code: 'a, b, c = map(float, input().split())\navg = (a + b + c) / 3\nprint(f"{avg:.2f}")',
      timeComplexity: 'O(1)',
      spaceComplexity: 'O(1)',
    },
    isPublished: true,
  },
];
